# Generated by Django 3.1.8 on 2021-08-01 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20210731_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shopping_carts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.shoppingcart'),
        ),
    ]
