# Generated by Django 3.1.8 on 2021-08-01 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_order_shopping_carts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shopping_carts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoppingcart_user_Id', to='sales.shoppingcart'),
        ),
    ]
