# Generated by Django 3.1.8 on 2021-08-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20210801_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shopping_carts',
        ),
        migrations.AddField(
            model_name='order',
            name='shopping_carts',
            field=models.ManyToManyField(null=True, related_name='shoppingcart_user_Id', to='sales.ShoppingCart'),
        ),
    ]
