# Generated by Django 3.1.8 on 2021-08-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20210801_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shopping_carts',
            field=models.ManyToManyField(null=True, to='sales.ShoppingCart'),
        ),
    ]
